// Curated writing resources for the Extra Tools feature
// All URLs are real, verified links to actual resources

export const WRITING_CONTESTS = [
  {
    name: 'Scholastic Art & Writing Awards',
    org: 'Alliance for Young Artists & Writers',
    deadline: 'Typically December (varies by region)',
    genres: ['Literary Fiction', 'Poetry', 'Science Fiction', 'Fantasy', 'Mystery', 'Horror', 'Non-fiction', 'Young Adult'],
    prize: 'Gold/Silver medals, scholarships up to $10,000',
    url: 'https://www.artandwriting.org/',
    description: 'The longest-running and most prestigious recognition program for creative teens in grades 7-12.',
  },
  {
    name: 'NaNoWriMo Young Writers Program',
    org: 'National Novel Writing Month',
    deadline: 'November (write all month)',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Horror', 'Historical Fiction', 'Thriller', 'Young Adult', "Children's"],
    prize: 'Completion badge, community recognition, winner goodies',
    url: 'https://ywp.nanowrimo.org/',
    description: 'A fun, empowering program that challenges young writers to complete a novel in 30 days.',
  },
  {
    name: 'Reedsy Short Story Contest',
    org: 'Reedsy',
    deadline: 'Weekly (new prompts every Friday)',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Horror', 'Thriller'],
    prize: '$250 weekly prize',
    url: 'https://blog.reedsy.com/short-story-contest/',
    description: 'A free weekly short story contest with creative prompts and cash prizes.',
  },
  {
    name: 'NYC Midnight Writing Competitions',
    org: 'NYC Midnight',
    deadline: 'Various throughout the year',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Mystery', 'Horror', 'Thriller', 'Romance'],
    prize: 'Cash prizes up to $5,000',
    url: 'https://www.nycmidnight.com/',
    description: 'Timed writing challenges where participants craft stories under creative constraints.',
  },
  {
    name: "Writer's Digest Annual Writing Competition",
    org: "Writer's Digest",
    deadline: 'Typically May',
    genres: ['Literary Fiction', 'Poetry', 'Science Fiction', 'Fantasy', 'Mystery', 'Romance', 'Horror', 'Thriller', 'Non-fiction'],
    prize: 'Grand prize $5,000 plus trip to conference',
    url: 'https://www.writersdigest.com/writers-digest-competitions',
    description: 'One of the oldest and most respected writing competitions with multiple genre categories.',
  },
  {
    name: 'Wattpad',
    org: 'Wattpad',
    deadline: 'Ongoing (various contests and Wattys annually)',
    genres: ['Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Horror', 'Thriller', 'Young Adult'],
    prize: 'Watty Awards, publishing deals, community recognition',
    url: 'https://www.wattpad.com/',
    description: 'The world\'s most popular social storytelling platform with annual Watty Awards and publishing opportunities.',
  },
  {
    name: 'YoungArts',
    org: 'National YoungArts Foundation',
    deadline: 'Typically October',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction', 'Young Adult'],
    prize: 'Up to $10,000 awards, mentorship, residencies',
    url: 'https://www.youngarts.org/',
    description: 'A national program identifying and nurturing the most accomplished young artists in the visual, literary, and performing arts.',
  },
  {
    name: 'Bennington Young Writers Awards',
    org: 'Bennington College',
    deadline: 'Typically November',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction'],
    prize: 'Publication and cash prizes',
    url: 'https://www.bennington.edu/events/young-writers-awards',
    description: 'A prestigious contest for high school students in poetry, fiction, and nonfiction.',
  },
  {
    name: 'Creative Writing Ink',
    org: 'Creative Writing Ink',
    deadline: 'Monthly prompts',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Poetry', 'Non-fiction'],
    prize: 'Publication on the site',
    url: 'https://creativewriting.ink/',
    description: 'A supportive writing community offering monthly writing prompts and publication opportunities.',
  },
  {
    name: 'The Adroit Journal',
    org: 'The Adroit Journal',
    deadline: 'Various submission windows',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction'],
    prize: 'Publication, prizes for annual contest',
    url: 'https://theadroitjournal.org/',
    description: 'An award-winning literary magazine with a special focus on publishing emerging and young writers.',
  },
  {
    name: 'Teen Ink',
    org: 'Teen Ink',
    deadline: 'Ongoing submissions',
    genres: ['Literary Fiction', 'Poetry', 'Fantasy', 'Science Fiction', 'Romance', 'Non-fiction', 'Young Adult'],
    prize: 'Publication in magazine, website, and books',
    url: 'https://www.teenink.com/',
    description: 'A national teen magazine, book series, and website devoted entirely to teen writing, art, and photos.',
  },
  {
    name: 'The Claremont Review',
    org: 'The Claremont Review',
    deadline: 'Submissions open annually',
    genres: ['Literary Fiction', 'Poetry'],
    prize: 'Publication and annual contest prizes',
    url: 'https://www.theclaremontreview.ca/',
    description: 'An international literary journal publishing the best poetry and fiction by writers aged 13-19.',
  },
  {
    name: 'Polyphony Lit',
    org: 'Polyphony Lit',
    deadline: 'Various submission windows',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction'],
    prize: 'Publication, editorial experience',
    url: 'https://www.polyphonylit.org/',
    description: 'A student-run international literary magazine for high school writers and editors.',
  },
  {
    name: 'Alliance for Young Artists & Writers Grants',
    org: 'Alliance for Young Artists & Writers',
    deadline: 'Varies by program',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction', 'Young Adult'],
    prize: 'Scholarships and grants for college-bound writers',
    url: 'https://www.artandwriting.org/scholarships/',
    description: 'Scholarship opportunities and grants for young writers recognized through the Scholastic Awards program.',
  },
  {
    name: 'National YoungArts Foundation Application',
    org: 'National YoungArts Foundation',
    deadline: 'Typically October',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction'],
    prize: 'Cash awards, mentorship, and nomination for U.S. Presidential Scholar in the Arts',
    url: 'https://www.youngarts.org/apply',
    description: 'Apply directly to the YoungArts program for recognition, awards, and career development opportunities.',
  },
];

export const RECOMMENDED_BOOKS = [
  {
    title: 'On Writing: A Memoir of the Craft',
    author: 'Stephen King',
    genres: ['Literary Fiction', 'Horror', 'Thriller', 'Non-fiction'],
    type: 'craft',
    description: 'Part memoir, part masterclass by one of the bestselling authors of all time on the craft and discipline of writing.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/10569.On_Writing',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AOn+Writing+au%3AStephen+King',
  },
  {
    title: 'Bird by Bird: Some Instructions on Writing and Life',
    author: 'Anne Lamott',
    genres: ['Literary Fiction', 'Non-fiction'],
    type: 'inspiration',
    description: 'A warm and funny guide to writing and life that encourages taking it one step at a time.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/12543.Bird_by_Bird',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3ABird+by+Bird+au%3AAnne+Lamott',
  },
  {
    title: 'The Elements of Style',
    author: 'William Strunk Jr. & E.B. White',
    genres: ['Non-fiction'],
    type: 'reference',
    description: 'The classic, definitive guide to clear and effective English writing, essential for every writer.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/33514.The_Elements_of_Style',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AThe+Elements+of+Style+au%3AStrunk',
  },
  {
    title: 'Steering the Craft',
    author: 'Ursula K. Le Guin',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction'],
    type: 'craft',
    description: 'A hands-on guide to the craft of narrative with exercises from one of the greatest speculative fiction writers.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/68024.Steering_the_Craft',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3ASteering+the+Craft+au%3ALe+Guin',
  },
  {
    title: 'Save the Cat! Writes a Novel',
    author: 'Jessica Brody',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Thriller', 'Young Adult'],
    type: 'craft',
    description: 'A step-by-step plotting guide that adapts the beloved Save the Cat! beat sheet method for novelists.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/32805475-save-the-cat-writes-a-novel',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3ASave+the+Cat+Writes+a+Novel+au%3ABrody',
  },
  {
    title: 'The Writing Life',
    author: 'Annie Dillard',
    genres: ['Literary Fiction', 'Non-fiction'],
    type: 'inspiration',
    description: 'A brilliant, poetic meditation on the solitary and sometimes agonizing art of writing.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/12530.The_Writing_Life',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AThe+Writing+Life+au%3AAnnie+Dillard',
  },
  {
    title: 'Writing Down the Bones: Freeing the Writer Within',
    author: 'Natalie Goldberg',
    genres: ['Literary Fiction', 'Poetry', 'Non-fiction'],
    type: 'inspiration',
    description: 'A Zen-inspired guide to freeing your creative voice through the practice of writing.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/44905.Writing_Down_the_Bones',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AWriting+Down+the+Bones+au%3ANatalie+Goldberg',
  },
  {
    title: 'Self-Editing for Fiction Writers',
    author: 'Renni Browne & Dave King',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Thriller'],
    type: 'craft',
    description: 'A practical guide to editing your own fiction covering show vs. tell, dialogue, point of view, and more.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/180467.Self_Editing_for_Fiction_Writers',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3ASelf-Editing+for+Fiction+Writers+au%3ABrowne',
  },
  {
    title: "The Emotion Thesaurus: A Writer's Guide to Character Expression",
    author: 'Angela Ackerman & Becca Puglisi',
    genres: ['Literary Fiction', 'Fantasy', 'Science Fiction', 'Mystery', 'Romance', 'Horror', 'Thriller'],
    type: 'reference',
    description: 'An indispensable reference listing body language, thoughts, and visceral responses for 130 emotions.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/43666740-the-emotion-thesaurus',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AThe+Emotion+Thesaurus+au%3AAckerman',
  },
  {
    title: 'Story: Substance, Structure, Style, and the Principles of Screenwriting',
    author: 'Robert McKee',
    genres: ['Literary Fiction', 'Thriller', 'Mystery'],
    type: 'craft',
    description: 'A comprehensive exploration of story structure and the principles that make narratives compelling across all media.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/241999.Story',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AStory+au%3ARobert+McKee',
  },
  {
    title: 'The Hero with a Thousand Faces',
    author: 'Joseph Campbell',
    genres: ['Fantasy', 'Science Fiction', 'Literary Fiction', 'Non-fiction'],
    type: 'inspiration',
    description: 'The groundbreaking study of the universal hero\'s journey pattern found in myths and stories worldwide.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/588138.The_Hero_With_a_Thousand_Faces',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AThe+Hero+with+a+Thousand+Faces+au%3ACampbell',
  },
  {
    title: 'Writing Fiction: A Guide to Narrative Craft',
    author: 'Janet Burroway',
    genres: ['Literary Fiction', 'Non-fiction'],
    type: 'craft',
    description: 'The most widely used creative writing textbook in America, covering every aspect of narrative craft.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/222117.Writing_Fiction',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AWriting+Fiction+au%3AJanet+Burroway',
  },
  {
    title: 'Zen in the Art of Writing',
    author: 'Ray Bradbury',
    genres: ['Literary Fiction', 'Science Fiction', 'Fantasy'],
    type: 'inspiration',
    description: 'A collection of exuberant essays on creativity and the joy of writing from the master of imaginative fiction.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/103761.Zen_in_the_Art_of_Writing',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AZen+in+the+Art+of+Writing+au%3ARay+Bradbury',
  },
  {
    title: 'The War of Art',
    author: 'Steven Pressfield',
    genres: ['Non-fiction'],
    type: 'inspiration',
    description: 'A powerful guide to overcoming creative resistance and the internal battles every writer faces.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/1319.The_War_of_Art',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3AThe+War+of+Art+au%3ASteven+Pressfield',
  },
  {
    title: 'Big Magic: Creative Living Beyond Fear',
    author: 'Elizabeth Gilbert',
    genres: ['Non-fiction'],
    type: 'inspiration',
    description: 'An inspiring exploration of creativity that encourages curiosity over fear in pursuing a creative life.',
    goodreadsUrl: 'https://www.goodreads.com/book/show/24453082-big-magic',
    libraryUrl: 'https://www.worldcat.org/search?q=ti%3ABig+Magic+au%3AElizabeth+Gilbert',
  },
];

export const WRITING_TOOLS_LIST = [
  {
    name: 'Grammarly',
    category: 'Grammar & Style',
    description: 'An AI-powered writing assistant that checks grammar, spelling, punctuation, and style in real time.',
    url: 'https://www.grammarly.com/',
    free: true,
  },
  {
    name: 'ProWritingAid',
    category: 'Grammar & Style',
    description: 'A comprehensive editing tool that analyzes style, grammar, overused words, and readability.',
    url: 'https://prowritingaid.com/',
    free: false,
  },
  {
    name: 'Hemingway Editor',
    category: 'Grammar & Style',
    description: 'Highlights complex sentences, passive voice, and readability issues to make your writing bold and clear.',
    url: 'https://hemingwayapp.com/',
    free: true,
  },
  {
    name: 'Google Docs',
    category: 'Writing Software',
    description: 'A free, cloud-based word processor with real-time collaboration and easy sharing.',
    url: 'https://docs.google.com/',
    free: true,
  },
  {
    name: 'Scrivener',
    category: 'Writing Software',
    description: 'A powerful writing app designed for long-form projects with tools for outlining, research, and drafting.',
    url: 'https://www.literatureandlatte.com/scrivener/overview',
    free: false,
  },
  {
    name: '4theWords',
    category: 'Writing Software',
    description: 'A gamified writing platform that turns your word count goals into an RPG adventure.',
    url: 'https://4thewords.com/',
    free: false,
  },
  {
    name: 'Wattpad',
    category: 'Community',
    description: 'The world\'s most popular social storytelling platform to share your writing and connect with readers.',
    url: 'https://www.wattpad.com/',
    free: true,
  },
  {
    name: 'Archive of Our Own',
    category: 'Community',
    description: 'A nonprofit fan-created archive for transformative works including fanfiction, with a supportive community.',
    url: 'https://archiveofourown.org/',
    free: true,
  },
  {
    name: 'RhymeZone',
    category: 'Research',
    description: 'A comprehensive rhyming dictionary and thesaurus for poets and songwriters.',
    url: 'https://www.rhymezone.com/',
    free: true,
  },
  {
    name: 'Behind the Name',
    category: 'Research',
    description: 'An etymology and history database of first names from around the world, perfect for naming characters.',
    url: 'https://www.behindthename.com/',
    free: true,
  },
  {
    name: 'World Anvil',
    category: 'Writing Software',
    description: 'A worldbuilding toolset for writers and game masters to create and organize fictional worlds.',
    url: 'https://www.worldanvil.com/',
    free: false,
  },
  {
    name: 'Campfire',
    category: 'Writing Software',
    description: 'A suite of writing tools for planning characters, magic systems, timelines, and entire story worlds.',
    url: 'https://www.campfirewriting.com/',
    free: false,
  },
  {
    name: 'Reedsy Book Editor',
    category: 'Publishing',
    description: 'A free online writing and formatting tool that exports publish-ready EPUB and PDF files.',
    url: 'https://reedsy.com/write-a-book',
    free: true,
  },
];
